### ISSUE TITLE
How to generate settings.jar?

### ISSUE THREAD

**Issue by sergiopvilar** [wimglenn/pycharm-dvorak-keymap#1]
I'm trying to port this project to OSX, how can I create the .jar?

Thanks!

**Comment by wimglenn** [comment]
Hi there Sergio, .jar files are basically zip files.  You should be able to create them in any archive manager program.  I used gnome's archive manager (file roller).  

On OSX, you might consider Karabiner as an alternative to the custom keymap.  It works well, I use that on my mac instead of mucking with the keymap.
